const KNOWLEDGE_BASE = [
  {
    title: "Remote Work Policy",
    tags: ["hr", "remote work", "hybrid"],
    content: "Employees may work remotely up to three days per week with manager approval. Core collaboration hours are 10:00–15:00 in the employee's primary time zone. Equipment and ergonomic assessments are provided."
  },
  {
    title: "Information Security Policy",
    tags: ["it", "security", "data"],
    content: "All confidential data must be stored in approved systems with MFA enabled. Customer data must never be downloaded to personal devices. Phishing simulations may occur without notice."
  },
  {
    title: "Time Off & Leave Policy",
    tags: ["hr", "vacation", "leave"],
    content: "Employees accrue paid vacation monthly and can carry over up to 10 days per calendar year. Extended leave requires documentation and HR review."
  }
];
function randomFloat(min, max) {
  return (Math.random() * (max - min) + min).toFixed(2);
}
function randomLatency() {
  return Math.floor(Math.random() * 250) + 120;
}
function retrieveRelevantDocs(question) {
  const q = question.toLowerCase();
  if (!q.trim()) return [];
  return KNOWLEDGE_BASE.filter(doc => {
    return doc.tags.some(t => q.includes(t.split(" ")[0])) ||
           q.includes(doc.title.toLowerCase().split(" ")[0]);
  });
}
function simulateAnswer(question) {
  if (!question.trim()) {
    return {
      answer: "Ask a question about HR, security, or remote work policies to see how this simulated RAG assistant might respond.",
      sources: []
    };
  }
  const docs = retrieveRelevantDocs(question);
  if (!docs.length) {
    return {
      answer: "I could not confidently match your question to a specific policy. In a real watsonx RAG pilot, this is where we would expand the corpus and refine retrieval parameters.",
      sources: []
    };
  }
  let answer = "Here's a synthesized answer based on the most relevant policy documents:\n\n";
  docs.forEach((doc, idx) => {
    answer += `${idx + 1}. From “${doc.title}”: ${doc.content}\n`;
  });
  answer += "\nIn a production pilot, this answer would be generated by an LLM grounded only in these retrieved passages, with strict citation and guardrails.";
  return { answer, sources: docs };
}
window.addEventListener("DOMContentLoaded", () => {
  const input = document.getElementById("mainInput");
  const sampleBtn = document.getElementById("sampleBtn");
  const clearBtn = document.getElementById("clearBtn");
  const runBtn = document.getElementById("runBtn");
  const extraControls = document.getElementById("extraControls");
  const outputPanel = document.getElementById("outputPanel");
  const outputBody = document.getElementById("outputBody");
  const metricConfidence = document.getElementById("metricConfidence");
  const metricLatency = document.getElementById("metricLatency");
  const metricPattern = document.getElementById("metricPattern");
  extraControls.innerHTML = `
    <div style="display:flex; gap:8px; flex-wrap:wrap;">
      <div class="field" style="flex:1;">
        <label for="modeSelect">Mode</label>
        <select id="modeSelect">
          <option value="qa">Q&A</option>
          <option value="search">Search-only</option>
        </select>
      </div>
      <div class="field" style="flex:1;">
        <label for="topK">Top-K documents</label>
        <input id="topK" type="number" min="1" max="5" value="2" />
      </div>
    </div>
  `;
  const modeSelect = document.getElementById("modeSelect");
  const topKInput = document.getElementById("topK");
  sampleBtn.addEventListener("click", () => {
    input.value = "What is the policy on working remotely and what hours am I expected to be available?";
  });
  clearBtn.addEventListener("click", () => {
    input.value = "";
    outputBody.innerHTML = "<p>Ask a question about HR or IT policies and click <strong>Run AI Analysis</strong> to see a simulated RAG-style response.</p>";
    outputPanel.querySelector(".output-header").innerHTML = '<span>Awaiting input...</span><span class="chip">No run yet</span>';
    metricConfidence.textContent = "-";
    metricLatency.textContent = "-";
    metricPattern.textContent = "-";
  });
  runBtn.addEventListener("click", () => {
    const question = input.value;
    const latency = randomLatency();
    const confidence = randomFloat(0.78, 0.96);
    const mode = modeSelect.value;
    const topK = Math.max(1, Math.min(5, parseInt(topKInput.value || "2", 10)));
    const result = simulateAnswer(question);
    const docs = result.sources.slice(0, topK);
    let headerChip = mode === "qa" ? "Grounded Q&A pattern" : "Semantic search pattern";
    outputPanel.querySelector(".output-header").innerHTML = '<span>Retrieval complete (simulated)</span><span class="chip">' + headerChip + '</span>';
    let bodyHtml = "";
    if (mode === "qa") {
      bodyHtml += "<p><strong>Assistant Answer (simulated)</strong></p>";
      bodyHtml += "<p>" + result.answer.replace(/\n/g, "<br>") + "</p>";
    }
    if (docs.length) {
      bodyHtml += "<p><strong>Retrieved Policy Snippets</strong></p><ul>";
      docs.forEach(doc => {
        bodyHtml += "<li><strong>" + doc.title + ":</strong> " + doc.content + "</li>";
      });
      bodyHtml += "</ul>";
    }
    if (!docs.length && mode === "search") {
      bodyHtml += "<p>No matching documents found in this small demo corpus. In a real engagement, we'd expand the content set and refine retrieval parameters.</p>";
    }
    outputBody.innerHTML = bodyHtml;
    metricConfidence.textContent = confidence;
    metricLatency.textContent = latency.toString();
    metricPattern.textContent = "Policy • RAG Prototype";
  });
});